"""Initial migration

Revision ID: a5e196f977bf
Revises: 22e1cafec445
Create Date: 2024-03-31 21:51:20.601892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e196f977bf'
down_revision = '22e1cafec445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
